config/routes.rb
AdUpload::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
  
  resources :global_settings
  resources :email_texts
  
  resources :upload_types do
    get :detailed_instructions
  end
  
  resources :jobs
  get 'myjobs', :to => "jobs#myjobs"

  resources :job_files do
    post :approve
    post :reject
    get :download
  end
end

app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessible :upload_type_id, :user_id, :name, :company, :salesrep, :acct_no, :address1, :address2, :city, :state, :zip,
     :email, :phonenum, :phonenum2, :fax, :startdate, :application, :application_other, :application_version, :platform, 
     :image_format, :vector_format, :color_spec, :job_type, :trapping, :files_to_run, :instructions, :job_files_attributes,
     :disclaimer
  
  belongs_to :upload_type
  belongs_to :user
  has_many :job_files, :dependent => :destroy
  accepts_nested_attributes_for :job_files, :allow_destroy => true
  
  # validates_acceptance_of :disclaimer, :allow_nil => false, :accept => true, :on => :create, :message=>'Must accept Terms of Service'
  validates_presence_of :name, :on => :create, :message=>'Name is required'
  # validates_presence_of :phonenum, :on => :create, :message=>'Phone number required'
  validates_presence_of :job_files, :on => :create, :message=>'Files to Upload are required'
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :require_admin, :only => [:edit, :update, :destroy]
  before_filter :require_edit_or_admin, :only => [:index]

  def index
    # Returns all jobs in database
    @jobs = Job
    @jobs = @jobs.where('name LIKE ? or company LIKE ?', "%#{params[:search_query]}%", "%#{params[:search_query]}%") if params[:search_query].present?
    @jobs = @jobs.paginate(:page => params[:page], :per_page => 20, :order => 'created_at DESC')
  end

  def myjobs
    jobs = Job
    # Display specific user if specified, otherwise display current users jobs
    if params[:user_id].nil?
      jobs = jobs.where(:user_id => current_user.id) unless current_user.nil?
    else
      jobs = jobs.where(:user_id=>params[:user_id])
    end
    @jobs = jobs.paginate(:page => params[:page], :per_page => 10, :order => 'created_at DESC')
  end

  def show
    @job = Job.find(params[:id])
    if @job.user_id != current_user.id and !((current_user.has_role? :edit) or (current_user.has_role? :admin))
      redirect_to myjobs_path
    end
  end

  def new
    if params[:upload_job_id].nil?
      redirect_to root_path
    end
    @upload_type = UploadType.find_by_id(params[:upload_job_id])
    @job = Job.new
    @job.startdate = Time.now
    10.times {@job.job_files.build}
    @global_settings = GlobalSettings.all
  end

  def create
    @global_settings = GlobalSettings.all
    @confirmation_email_text = EmailText.find_by_name_and_email_type('Upload New Job', 'confirmation')
    @notification_email_text = EmailText.find_by_name_and_email_type('Upload New Job', 'notification')
    @current_user = current_user

    if params[:cancel_button]
      redirect_to root_path
    else
      @job = Job.new(params[:job])
      @job.user_id = current_user.id
      @upload_type = UploadType.find_by_id(@job.upload_type_id)
      if @job.save
        Rails.logger.info '*** New job saved ***'
        Notification.job_uploaded_notification(@upload_type,@job,@notification_email_text).deliver
        Confirmation.confirmation_new_job(@upload_type,@job,@current_user.email,@confirmation_email_text).deliver
        if @job.email != @current_user.email
          Confirmation.confirmation_new_job(@upload_type,@job,@job.email,@confirmation_email_text).deliver
        end
        flash[:notice] = "Job Created"
        redirect_to root_path
      else
        # retain selected files if save fails
        (10 - @job.job_files.size).times { @job.job_files.build }
        flash[:error] = "Job Creation Failed"
        render :action => :new
      end
    end    
  end
  
  def edit
  end

  def update
  end

  def destroy
    @job = Job.find(params[:id])
    if @job.destroy
      flash[:notice] = "Job Killed!"
      redirect_to jobs_path
    else
      flash[:error] = "Job Deletion Failed"
      redirect_to jobs_path
    end
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_new_file.html.erb
<%= form.fields_for :job_files, :html=>{ :multipart => true } do |f| %>
	<li class="files_to_upload">
		<%= f.file_field :file %>
	</li>
<% end %>

app/views/jobs/_table_row.html.erb
<tr>
	<td><div class="text-center"><%= table_row.id %></div></td>
	<td><div class="text-center"><%= table_row.upload_type.name %></div></td>
	<td><%= table_row.name %></td>
	<td><%= table_row.company %></td>
	<td><div class="text-center"><%= table_row.created_at.strftime('%m/%d/%Y') %> at <%= table_row.created_at.strftime('%I:%M%p') %></div></td>
	<td>
		<div class="text-center">
			<ul class="list-inline">
				<li>
					<%= link_to "Show", job_path(table_row), :class => 'btn btn-mini' %>
				</li>
				<% if current_user.has_role? :admin %>
					<li>
						<%= link_to "Delete", job_path(table_row), 
									:method => :delete, 
									:confirm => "Are you sure you want to delete job?",
									:action => 'destroy',
									:class => 'btn btn-mini' %>
					</li>
				<% end %>
			</ul>
		</div>
	</td>
</tr>

app/views/jobs/index.html.erb
<div id="jobs-page">
	<div id="page-content" class="clearfix">
		<h1>
			All Jobs
			<div class="pull-right">
				<%= form_tag jobs_path , :method => :get do %>
					<table cellspacing="0" cellpadding="0">
						<tbody>
							<td class="medium">
								<td><%= search_field_tag :search_query, params[:search_query], :placeholder => "search users", :autofocus => true %></td>
							<td>&nbsp;&nbsp;</td>
							<td class="smaller"><%= submit_tag "Search", :class => 'submit'%></td>
						</tbody>
					</table>
				<% end %>
			</div>
		</h1>

		<div class="inner-box clearfix">
		  <div id="form-block" class="grid_15">
			  <% if @jobs %>
			    <div id="table-block" class="grid_15">
			      <% unless @jobs.nil? %>
			        <table class="table table-bordered table-hover table-condensed">
			          <tbody>
			            <thead>
										<tr>
				              <th><div class="text-center">Job #</div></th>
				              <th><div class="text-center">Upload Type</div></th>
				              <th><div>Name</div></th>
				              <th><div>Company<div></th>
				              <th><div class="text-center"</div>Uploaded</div></th>
				              <th><div class="text-center">Action</div></th>
										</tr>
			            </thead>
			            <%= render :partial => 'table_row', :collection => @jobs %>
			          </tbody>
				      </table>
							<div id="table-paginate">
				      	<div class="pull-right"><%= will_paginate @jobs, :class => "pagination-small" %></div>
							</div>
			      <% end %>
			    </div>
			  <% end %>
			</div>
		</div>
	</div>
</div>

app/views/jobs/myjobs.html.erb
<div id="jobs-page">
	<div id="page-content" class="clearfix">
		<h1>
			Jobs <%= "for "+@jobs.first.user.name unless @jobs.first.nil? %>
		</h1>
		<span class="pull-right"></span>

		<div class="inner-box clearfix">
		  <div id="form-block" class="grid_15">
			  <% if @jobs %>
			    <div id="table-block" class="grid_15">
			      <% unless @jobs.nil? %>
			        <table class="table table-bordered table-hover table-condensed">
			          <tbody>
			            <thead>
										<tr>
				              <th><div class="text-center">Job #</div></th>
				              <th><div class="text-center">Upload Type</div></th>
				              <th><div>Name</div></th>
				              <th><div>Company<div></th>
				              <th><div class="text-center"</div>Uploaded</div></th>
				              <th><div class="text-center">Action</div></th>
										</tr>
			            </thead>
			            <%= render :partial => 'table_row', :collection => @jobs %>
			          </tbody>
				      </table>
							<div id="table-paginate">
				      	<div class="pull-right"><%= will_paginate @jobs, :class => "pagination-small" %></div>
							</div>
			      <% end %>
			    </div>
			  <% end %>
			</div>
		</div>
	</div>
</div>

app/views/jobs/new.html.erb
<div id="jobs-page">
	<div id="page-content" class="clearfix">
		<h1>Upload New Job</h1>

		<div class="inner-box clearfix">
		  <div id="form-block" class="grid_15">
				<%= form_for @job, :url => jobs_path, :html => {:multipart => true} do |form| %>
					<p>Fill out the form below, browse for the file to upload, and press the submit button. If your file is large, be patient and wait for the successful upload screen. You will receive an email confirmation upon successful upload.</p>
					<p>Required fields are marked with an asterisk *.</p>

					<%= form.hidden_field :upload_type_id, :value => @upload_type.id %>

					<fieldset>
						<div class="well well-small controls controls-row">
							<div class="span3">
								<label>Name: *</label><%= form.text_field :name, :class => "large", :autofocus => true,
										:value=>current_user.name %>
								<%= error_messages(@job, "name") %>
							</div>
							<div class="span3">
								<label>Company:</label><%= form.text_field :company, :value=>current_user.company %>
								<label>Account #:</label><%= form.text_field :acct_no, :value=>current_user.acct_no %>
								<label>Sales Rep:</label><%= form.text_field :salesrep %>
							</div>
							<div class="span3">
								<label>Email:</label><%= form.text_field :email, :required => true, :value=>current_user.email %>
							</div>
							<div class="span2">
								<label>Phone Numbers:</label><%= form.text_field :phonenum, :value=>current_user.phonenum %>
								<%= error_messages(@job, "phonenum") %>
								<%= form.text_field :phonenum2, :value=>current_user.phonenum2 %>
								<label>Fax #:</label><%= form.text_field :fax, :value=>current_user.fax %>
							</div>
						</div>

						<div class="well well-small">
							<div class="form-horizontal">
								<div class="control-group">
										<label class="control-label" for="address1">Street Address:</label>
										<div class="controls"><%= form.text_field :address1, :value=>current_user.address1 %></div>
								</div>
								<div class="control-group">
									<label class="control-label" for="address2">Address2 or PO:</label>
									<div class="controls"><%= form.text_field :address2, :value=>current_user.address2 %></div>
							  </div>				
								<div class="control-group">
									<label class="control-label" for="city">City/State/Zip:</label>
									<div class="controls">
										<%= form.text_field :city, :value=>current_user.city, :size => 20, :maxlength => 20, :class=>"input-medium" %>
										<%= form.text_field :state, :value=>current_user.state, :size => 2, :maxlength => 2, :class=>"input-mini" %>
										<%= form.text_field :zip, :value=>current_user.zip, :size => 5, :maxlength => 5, :class=>"input-mini" %>
									</div>
							  </div>
							</div>
						</div>

						Job Info:
						<div class="well well-small">
							<% if @upload_type.get_startdate %>
								StartDate: <%= form.date_select(:startdate, {
																			:include_blank => true,
																			:start_year => Time.now.year,
																			:end_year => Time.now.year+1,
																			:use_month_numbers => true,  
																			:order => [:month, :day, :year]},
																		{:class => "input-small"}) %>
							<% end %><br/>

							<% if @upload_type.get_application_used %>
								Application: Indicate which program the job was created in:<br/>
								<%= form.select :application, 
																options_for_select(['InDesign', 'Adobe PDF', 'Quark', 'PageMaker', 
																										'Illustrator', 'Photoshop', 'Freehand', 'Other']), 
																:prompt=>'- Select Application -' %>
								If other, indicate: <%= form.text_field :application_other, :class => "input-medium" %>
								Version: <%= form.text_field :application_version, :class => "input-small" %>
							<% end %><br/>
							
							<% if @upload_type.get_platform %>
								<label class="radio inline">
							    <%= form.label :platform, "Platform:" %>
							  </label>
								<label class="radio inline">
							    <%= form.radio_button :platform, "Mac", :checked => true %> Mac
							  </label>
								<label class="radio inline">
							    <%= form.radio_button :platform, "Windows" %> Windows
							  </label>
							<% end %><br/>

							<% if @upload_type.get_image_format %>
								Image Formats Used: 
								<label class="checkbox inline"><%= form.check_box :image_format %>TIFF</label>
								<label class="checkbox inline"><%= form.check_box :image_format %>JPG</label>
								<label class="checkbox inline"><%= form.check_box :image_format %>EPS</label>
							<% end %><br/>

							<% if @upload_type.get_vector_format %>
								Vectored Formats Used: 
								<label class="checkbox inline"><%= form.check_box :vector_format %>EPS</label>
								<label class="checkbox inline"><%= form.check_box :vector_format %>AI</label>
								<label class="checkbox inline"><%= form.check_box :vector_format %>FH</label>
							<% end %><br/>

							<% if @upload_type.get_color_spec %>
								<label class="radio inline">
							    <%= form.label :color_spec, "Color Spec:" %>
							  </label>
								<label class="radio inline">
							    <%= form.radio_button :color_spec, "B/W", :checked => true %> B/W
							  </label>
								<label class="radio inline">
							    <%= form.radio_button :color_spec, "Color" %> Color
							  </label>
							<% end %><br/>

							<% if @upload_type.get_job_type %>
								<label class="radio inline">
							    <%= form.radio_button :job_type, "Coupon" %> Coupon
							  </label>
								<label class="radio inline">
							    <%= form.radio_button :job_type, "Heavy Reverse" %> Heavy Reverse
							  </label>
							<% end %><br/>

							<% if @upload_type.get_trapping %>
								<label class="radio inline">
							    <%= form.label :color_spec, "Trapping: Have you applied Traps? " %>
							  </label>
								<label class="radio inline">
							    <%= form.radio_button :trapping, "Yes" %> Yes
							  </label>
								<label class="radio inline">
							    <%= form.radio_button :trapping, "No", :checked => true %> No
							  </label>
							<% end %><br/>

							<% if @upload_type.get_files_to_run %>
								Files to Run: <%= form.text_field :files_to_run %>
								<span class="help-inline">Comma-separated list of files to run</span>
							<% end %><br/>
						</div>

						Files to Upload: *
						<%= error_messages(@job, "job_files") %>
						<div class="well well-small clearfix">
							<p>Browse your system and locate the file(s) to upload for this job.</p>

							<ul class="inline">
								<%= render :partial => 'new_file', :locals => {:form => form} %>
							</ul>
						</div>

						<label>Instructions:</label><%= form.text_area :instructions, :style=>"width:80%;height:100px",
									:placeholder=>"Enter any special instructions for this job" %>

					<label class="checkbox">
				    <!-- <%= form.check_box :disclaimer %> -->
						<% @global_settings.each do |setting| %>
							<p>* <%= setting.disclaimer.html_safe if setting.disclaimer %></p>
						<% end %>
						<p><%= link_to "Review Upload Instructions", upload_type_detailed_instructions_path(@upload_type), 
														class: 'btn btn-mini btn-info', :target => "_blank" %></p>
						<%= error_messages(@job, "disclaimer") %>
				  </label>

						<br/>
						<%= form.submit "Create", :class => 'submit small progress_bar'%>
						<%= form.submit "Cancel", :name => 'cancel_button', :class => 'submit small'%>
					</fieldset>
					<div id="ProgressModal" class="modal fade">
						<div class="modal-header text-center">
							<h3>Uploading Files</h3><img class="spinner" src="/assets/Spinner.gif">
						</div>
						<div class="modal-body text-center">
							Please be patient while we upload your files. Thank you.
						</div>
						<div class="modal-body text-center">
							You will be sent a confirmation email upon successful upload
						</div>
					</div>
					
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/jobs/show.html.erb
<div id="jobs-page">
	<div id="page-content" class="clearfix">
		<h3>
			Job #<%= @job.id %>
			<span class="pull-right">
				<%= mail_to @job.upload_type.email_replyto, "Email Us", :class=>"btn btn-primary", :target => "_blank" %>
			</span>
		</h3>

		<div class="inner-box clearfix">
		  <div id="form-block" class="grid_15">
				<%= form_for @job do |form| %>
					<fieldset>
						<div class="well well-small controls controls-row">
							<div class="span3">
								<h5>Contact Info:</h5>
								Name: <%= @job.name %><br/>
								<% if @job.company.nil? %>Company: <%= @job.company %><br/><% end %>
								<% if @job.salesrep.nil? %>Sales Rep: <%= @job.salesrep %><br/><% end %>
								<% if @job.acct_no.nil? %>Account #: <%= @job.acct_no %><br/><% end %>
							</div>
							<div class="span3">
								<h5>Address:</h5>
								<%= @job.address1 %><br/>
								<% if @job.address2.nil? %><%= @job.address2 %><br/><% end %>
								<%= @job.city %>, <%= @job.state %> <%= @job.zip %><br/>
							</div>
							<div class="span3">
								<h5>Contact Info:</h5>
								Email: <%= @job.email %><br/>
								Phone Numbers: 
								<%= @job.phonenum %>
								<% if @job.phonenum2.nil? %>, <%= @job.phonenum2 %><% end %><br/>
								Fax #: <%= @job.fax %><br/>
							</div>
						</div>

						<h5>Job Info:</h5>
						<div class="well well-small">
							<% if @job.upload_type.get_startdate and @job.startdate? %>
								StartDate: <%= @job.startdate.strftime('%m/%d/%y') %><br/>
							<% end %>

							<% if @job.upload_type.get_application_used %>
								Application: 
								<% if @job.application.present? %>
									<%= @job.application %>
								<% else %>
									<%= @job.application_other %>
								<% end %>
								<%= @job.application_version %><br/>
							<% end %>
							
							<% if @job.upload_type.get_platform %>
						    Platform: <%= @job.platform %><br/>
							<% end %>

							<% if @job.upload_type.get_image_format %>
								Image Formats Used: <%= @job.image_format %><br/> 
							<% end %>

							<% if @job.upload_type.get_vector_format %>
								Vectored Formats Used: <%= @job.vector_format %><br/>
							<% end %>

							<% if @job.upload_type.get_color_spec %>
								Color Spec: <%= @job.color_spec %></br>
							<% end %>

							<% if @job.upload_type.get_job_type %>
								Job Type:
								<% if @job.job_type %>
						    	Coupon
								<% else %>
						    	Heavy Reverse
								<% end %>	
								<br/>
							<% end %>

							<% if @job.upload_type.get_trapping %>
								Trappings? 
								<% if @job.trapping %>
						    	Yes
								<% else %>
						    	No
								<% end %>	
								<br/>
							<% end %>

							<% if @job.upload_type.get_files_to_run %>
								Files to Run: <%= @job.files_to_run %>
							<% end %><br/>
						</div>

						<h5>Instructions:</h5>
						<div class="well well-small">
							<%= @job.instructions %>
						</div>

						<div class="clearfix">
							<div class="span4">
								<h5>Original Files Uploaded with Job:</h5>
								<i>(click filename to download)</i>
								<div class="well well-small clearfix">
									<% @job.job_files.job_files.each do |file| %>
										<ul class="">
											<li>
												<%= link_to file.file_file_name, job_file_download_path(file) %> - 
												<%= file.file_updated_at.strftime('%m/%d/%y at %I:%M%p') %>
												<% if (current_user.has_role? :edit) or (current_user.has_role? :admin) %>
													<div class="pull-right">
														<%= link_to "X", job_file_path(file), 
																	:method => :delete, 
																	:confirm => "Are you sure you want to delete file?",
																	:action => 'destroy',
																	:class => 'btn btn-mini' %>
													</div>
												<% end %>
												<br/>
											</li>
										</ul>
									<% end %>
									<% if current_user.id == @job.user_id %>
										<%= link_to "Upload Additional File", new_job_file_path(:job_id=>@job, :file_type=>"job_file"),
													:class=>"btn btn-primary btn-mini" %>
									<% end %>
								</div>
								<h5>Worked Files:</h5>
								<i>(click filename to download)</i>
								<div class="well well-small clearfix">
									<% @job.job_files.worked_files.each do |file| %>
										<ul class="">
											<li>
												<%= link_to file.file_file_name, job_file_download_path(file) %> - 
												<%= file.file_updated_at.strftime('%m/%d/%y at %I:%M%p') %>
												<% if (current_user.has_role? :edit) or (current_user.has_role? :admin) %>
													<div class="pull-right">
														<%= link_to "X", job_file_path(file), 
																	:method => :delete, 
																	:confirm => "Are you sure you want to delete file?",
																	:action => 'destroy',
																	:class => 'btn btn-mini' %>
													</div>
												<% end %>
												<br/>
											</li>
										</ul>
									<% end %>
									<% if (current_user.has_role? :edit) or (current_user.has_role? :admin) %>
										<%= link_to "Upload Worked File", new_job_file_path(:job_id=>@job, :file_type=>"worked_file"), 
													:class=>"btn btn-primary btn-mini" %>
									<% end %>
								</div>
							</div>
							<div class="span8">
								<h5>Proof Files:</h5>
								<i>(click proof to download)</i>
								<div class="well well-small clearfix">
									<div class="clearfix">
										<% @job.job_files.proof_files.each do |file| %>
											<ul class="unstyled pull-left">
												<li class="attached_file_box text-center">
													<div id="image_<%= file.id%>" class="file_thumb">
														<div class="file_thumb_image">
															<% if file.file_content_type == 'application/postscript' %>
																<a title="By Everaldo Coelho (YellowIcon) [LGPL (http://www.gnu.org/licenses/lgpl.html)], via Wikimedia Commons" 
																		href="http://commons.wikimedia.org/wiki/File%3AMime_postscript.png">
																	<img class="ps_image" width="256" alt="Mime postscript"
																		src="//upload.wikimedia.org/wikipedia/commons/f/fc/Mime_postscript.png"/>
																</a>
															<% else %>
																<% if file.file_content_type == 'application/zip' %>
																	<a title="By Alexander Rauchfuss [see page for license], via Wikimedia Commons" href="http://commons.wikimedia.org/wiki/File%3ASimple_Comic_zip.png"><img width="512" alt="Simple Comic zip" src="//upload.wikimedia.org/wikipedia/commons/f/fa/Simple_Comic_zip.png"/></a>
																<% else %>
																	<%= link_to image_tag(file.file.url(:thumb), :alt=>"File"), 
																							job_file_download_path(file) %>
																<% end %>
															<% end %>
															<% if (current_user.has_role? :edit) or (current_user.has_role? :admin) %>
																<div class="file_thumb_delete_icon">
																	<%= link_to "X", job_file_path(file), 
																				:method => :delete, 
																				:confirm => "Are you sure you want to delete file?",
																				:action => 'destroy',
																				:class => 'btn btn-mini' %>
																</div>
															<% end %>
														</div>
													</div>
													<%= file.file_file_name %>
													<% if file.approved %>
														<br/><i class="icon-check"></i>
														<%= file.approved_at.strftime('%m/%d/%y at %I:%M%p') unless file.approved_at.nil? %>
													<% else %>
														<% if file.rejected %>
															<br/><i class="icon-remove"></i>
															<%= file.rejected_at.strftime('%m/%d/%y at %I:%M%p') unless file.rejected_at.nil? %>
														<% else %>
															</br><%= link_to "Approve Proof?", job_file_approve_path(:job_file_id=>file.id, :approve => true), 
																		:method => :post, 
																		:confirm => "Are you sure you want to approve this proof?",
																		:class=>"btn btn-primary btn-mini approve_btn" %>
															</br><%= link_to "Reject Proof?", job_file_reject_path(:job_file_id=>file.id, :reject => true), 
																		:method => :post, 
																		:confirm => "Are you sure you want to reject this proof?",
																		:class=>"btn btn-primary btn-mini reject_btn" %>
														<% end %>
													<% end %>
												</li>
											</ul>
										<% end %>
									</div>
									<% if (current_user.has_role? :edit) or (current_user.has_role? :admin) %>
										<br/><%= link_to "Upload Proof", new_job_file_path(:job_id=>@job.id, :file_type=>"proof_file"), 
													:class=>"btn btn-primary btn-mini" %>
									<% end %>
									<% if @job.job_files.present? %>
										<div class="pull-right">
											<div class="checkbox"><i class="icon-check"></i> = Approved Proof </div>
											<div class="checkbox"><i class="icon-remove"></i> = Rejected Proof </div>
										</div>
									<% end %>
								</div>
							</div>
						</div>

					</fieldset>
				<% end %>
		</div>
	</div>
</div>