config/routes.rb
AdUpload::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
  
  resources :global_settings
  resources :email_texts
  
  resources :upload_types do
    get :detailed_instructions
  end
  
  resources :jobs
  get 'myjobs', :to => "jobs#myjobs"

  resources :job_files do
    post :approve
    post :reject
    get :download
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me,
                  :company, :acct_no, :phonenum, :phonenum2, :fax, :address1, :address2, :city, :state, :zip
  
  before_create :set_default_role
  after_create :send_welcome_email 
  
  has_many :jobs
  
  validates_presence_of :name, :message=>'Name is required'

  private
  def set_default_role
    self.add_role :view
  end

  def send_welcome_email
    Confirmation.confirmation_new_register(self).deliver
  end  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :require_admin, :only => [:index, :show, :destroy]

  def index
    @users = User.find(:all, :order=>'name')
  end

  def show
    @user = User.find(params[:id])
  end
  
  def edit
    @user = User.find(params[:id])
    if !(current_user.has_role? :admin) and !(current_user == @user)
      redirect_to root_path
    end
  end

  def update
    if params[:cancel_button]
      redirect_to users_path
    else
      @user = User.find(params[:id])
      if @user.update_attributes(params[:user])
        flash[:notice] = "User updated"
        redirect_to users_path, :notice => "User updated."
      else
        flash[:error] = "Unable to update user"
        render :action => :edit, :alert => "Unable to update user."
      end
    end
  end

  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      flash[:notice] = "User deleted"
      redirect_to users_path, :notice => "User deleted."
    else
      flash[:error] = "Unable to delete user"
      redirect_to users_path, :notice => "Unable to delete user."
    end
  end
end

app/views/users/_user.html.erb
<div id="role-options-<%= user.id %>" class="modal" style="display: none;">
  <%= simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-vertical' } do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Change Role</h3>
    </div>
    <div class="modal-body">
      <%= f.input :role_ids, 
				:collection => Role.all.sort_by { |obj| obj.sort_order }, 
				:as => :radio_buttons, 
				:label_method => lambda {|t| t.name.titleize+"  - "+t.description}, 
				:label => false, 
				:item_wrapper_class => 'inline', 
				checked: user.role_ids.first %>
    </div>
    <div class="modal-footer">
      <%= f.submit "Change Role", :class => "btn" %>
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div id="upload_types-page">
	<div id="page-content" class="clearfix">
		<h3>
			Login: <%= @user.email %>
			<span class="pull-right">
				<%= link_to "All Users", users_path, :class=>"btn btn-primary" if (current_user.has_role? :admin) %>
			</span>
		</h3>

		<div class="inner-box clearfix">
		  <div id="form-block" class="grid_15">
				<%= form_for @user, :url => user_path do |form| %>
					<fieldset>
						<% if (current_user == @user) %>
							<div class="well well-small controls controls-row">
							  <%= link_to "Change Password", edit_user_registration_path, :class=>"btn btn-mini" %>
							</div>
						<% end %>

						<div class="well well-small controls controls-row">
							<div class="span3">
							  <label>Name:</label><%= form.text_field :name %>
								<%= error_messages(@user, "name") %>
								<label>Company:</label><%= form.text_field :company %>
								<label>Account #:</label><%= form.text_field :acct_no %>
							</div>
							<div class="span2">
								<label>Phone Numbers:</label><%= form.text_field :phonenum, :size => 12, :maxlength => 12, :class=>"input-medium" %>
								<%= form.text_field :phonenum2, :size => 12, :maxlength => 12, :class=>"input-medium" %>
								<label>Fax #:</label><%= form.text_field :fax, :size => 12, :maxlength => 12, :class=>"input-medium" %>
							</div>
							<div class="span6">
								<div class="form-horizontal">
									<div class="control-group">
											<label class="control-label" for="address1">Street Address:</label>
											<div class="controls"><%= form.text_field :address1 %></div>
									</div>
									<div class="control-group">
										<label class="control-label" for="address2">Address2 or PO:</label>
										<div class="controls"><%= form.text_field :address2 %></div>
								  </div>				
									<div class="control-group">
										<label class="control-label" for="city">City/State/Zip:</label>
										<div class="controls">
											<%= form.text_field :city, :size => 20, :maxlength => 20, :class=>"input-medium" %>
											<%= form.text_field :state, :size => 2, :maxlength => 2, :class=>"input-mini" %>
											<%= form.text_field :zip, :size => 5, :maxlength => 5, :class=>"input-mini" %>
										</div>
								  </div>
								</div>
							</div>
						</div>
						<br/>
						<%= form.submit "Update", :class => 'submit small'%>
						<%= form.submit "Cancel", :name => 'cancel_button', :class => 'submit small'%>
					</fieldset>
				<% end %>
			</div>
	  </div>
	</div>
</div>

app/views/users/index.html.erb
<h3>Users</h3>
<div>
	<table class="table table-condensed table-striped table-bordered table-hover">
	  <thead>
	    <tr>
	      <th><div class="text-center">Username</div></th>
	      <th><div class="text-center">Email</div></th>
	      <th><div class="text-center">Registered</div></th>
	      <th><div class="text-center">Role</div></th>
	      <th><div class="text-center">Jobs</div></th>
	      <th><div class="text-center">Account</div></th>
	    </tr>
	  </thead>
	  <tbody>
		  <% @users.each do |user| %>
		    <tr>
		      <td><%= link_to user.name, user unless user.nil? %></td>
		      <td><%= user.email %></td>
		      <td>
						<div class="text-center">
							<%= user.created_at.strftime('%m/%d/%Y') %> at <%= user.created_at.strftime('%I:%M%p') %>
						</div>
					</td>
		      <td>
						<div class="text-center">
							<%= user.roles.last.name.titleize unless user.roles.last.nil? %>
							<a data-toggle="modal" href="#role-options-<%= user.id %>" class="btn btn-mini" type="button">Change role</a>
							<%= render user %>
						</div>
					</td>
					<td>
						<div class="text-center">
							<% if user.jobs.present? %>
								<%= link_to("List Jobs", myjobs_path(:user_id => user), :class => 'btn btn-mini') %>
							<% end %>
						</div>
					</td>
					<td>
						<div class="text-center">
							<ul class="list-inline">
								<li><%= link_to("Edit", edit_user_path(user), :class => 'btn btn-mini') %></li>
								<li><%= link_to("Delete", user_path(user), 
													:data => { :confirm => "Are you sure you want to delete user?" }, 
													:method => :delete, 
													:class => 'btn btn-mini') if (user != current_user) and (current_user.has_role? :admin) %></li>
							</ul>
						</div>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>