config/routes.rb
AdUpload::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
  
  resources :global_settings
  resources :email_texts
  
  resources :upload_types do
    get :detailed_instructions
  end
  
  resources :jobs
  get 'myjobs', :to => "jobs#myjobs"

  resources :job_files do
    post :approve
    post :reject
    get :download
  end
end

app/controllers/upload_types_controller.rb
class UploadTypesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :require_admin, :only => [:index, :new, :edit, :update, :destroy]

  def index
    @upload_types = UploadType.find(:all, :order => 'tab_sort')
  end

  def show
    @upload_type = UploadType.find(params[:id])
  end

  def detailed_instructions
    @upload_type = UploadType.find(params[:upload_type_id])
    render :layout => "detailed_instructions"
  end

  def new
    @upload_type = UploadType.new
  end

  def create
    if params[:cancel_button]
      redirect_to global_settings_path
    else
      @upload_type = UploadType.new(params[:upload_type])
      if @upload_type.save
        flash[:notice] = "Upload Type Created"
        redirect_to global_settings_path
      else
        flash[:error] = "Upload Type Creation Failed"
        render :action => :new
      end
    end    
  end

  def edit
    @upload_type = UploadType.find(params[:id])
  end

  def update
    if params[:cancel_button]
      redirect_to global_settings_path
    else
      @upload_type = UploadType.find(params[:id])
      if @upload_type.update_attributes(params[:upload_type])
        flash[:notice] = "Upload Type Updated"
        redirect_to global_settings_path
      else
        flash[:error] = "Upload Type Creation Failed"
        render :action => :edit
      end
    end
  end

  def destroy
    @upload_type = UploadType.find(params[:id])
    @jobs_count = Job.where(:upload_type_id => @upload_type).count
    Rails.logger.info @jobs_count
    if @jobs_count == 0
      if @upload_type.destroy
        flash[:notice] = "Upload Type Killed!"
        redirect_to global_settings_path
      else
        flash[:error] = "Upload Type Deletion Failed"
        redirect_to global_settings_path
      end
    else
      flash[:error] = "Deletion Failed: Jobs still exist for Upload Type"
      redirect_to global_settings_path
    end
  end
end

app/helpers/upload_types_helper.rb
module UploadTypesHelper
end

app/views/upload_types/_table_row.html.erb
<tr>
	<td><div class="text-center"><%= table_row.tab_sort %></div></td>	
	<td><%= table_row.name %></td>	
	<td><%= table_row.tab_name %></td>	
	<td class="center">
		<div class="text-center">
	  	<%= link_to("Edit", edit_upload_type_path(table_row), :class => 'btn btn-mini') %>
	  	<%= link_to("Delete Type", upload_type_path(table_row), 
									:data => { :confirm => "Are you sure you want to delete this upload type?" }, 
									:method => :delete, 
									:class => 'btn btn-mini') %>
		</div>
	</td>
</tr>

app/views/upload_types/detailed_instructions.html.erb
<div id="upload_types-page">
	<div id="page-content" class="clearfix">
		<div class="inner-box clearfix">
		  <div id="form-block" class="grid_15">
				<p><%= @upload_type.detailed_instructions.html_safe if @upload_type.detailed_instructions %></p>
			</div>
		</div>
	</div>
</div>

app/views/upload_types/edit.html.erb
<div id="upload_types-page">
	<div id="page-content" class="clearfix">
		<h3>Upload Type: <%= @upload_type.name %></h3>

		<div class="inner-box clearfix">
		  <div id="form-block" class="grid_15">
				<%= form_for @upload_type, :url => upload_type_path do |form| %>
					<fieldset>
						<label>Name:</label>
						<%= form.text_field :name, :class => "large", :placeholder=>"Enter name of upload type" %>
						<%= error_messages(@upload_type, "name") %>

						<label>Tab Name:</label>
						<%= form.text_field :tab_name, :class => "large", :placeholder=>"Enter name for menu tab" %>
						<%= error_messages(@upload_type, "tab_name") %>
						<label>Tab Sort Order:</label>
						<%= form.text_field :tab_sort, :class => "large", :placeholder=>"Order to display tab in the navbar" %>
						<%= error_messages(@upload_type, "tab_sort") %>

						<label>Description:</label>
						<%= form.text_area :description, :style=>"width:80%;height:100px", :placeholder=>"Enter description" %>
									
						<label>Upload Instructions:</label>
						<%= form.text_area :instructions, :style=>"width:80%;height:400px", :placeholder=>"Enter instructions for user" %>

						<label>Detailed Instructions about creating press-ready files:</label>
						<%= form.text_area :detailed_instructions, :style=>"width:80%;height:400px", :placeholder=>"Enter detailed instructions for user" %>

						<div class="well well-small">
							<ul class="unstyled">
							Upload Prompts to include:
								<li><label class="checkbox"><%= form.check_box :get_startdate %>StartDate</label></li>
								<li><label class="checkbox"><%= form.check_box :get_application_used %>Application Used (ie. InDesign, PhotoShop,...)</label></li>
								<li><label class="checkbox"><%= form.check_box :get_platform %>Platform (ie. Mac/Windows)</label></li>
								<li><label class="checkbox"><%= form.check_box :get_image_format %>Image Format (ie. TIFF, JPG,...)</label></li>
								<li><label class="checkbox"><%= form.check_box :get_vector_format %>Vector Format (ie. EPS, AI,...)</label></li>
								<li><label class="checkbox"><%= form.check_box :get_color_spec %>Color Spec (BW or Color)</label></li>
								<li><label class="checkbox"><%= form.check_box :get_job_type %>Job Types (ie. Coupon, Reverse,...)</label></li>
								<li><label class="checkbox"><%= form.check_box :get_trapping %>Trapping Applied?</label></li>
								<li><label class="checkbox"><%= form.check_box :get_files_to_run %>List of Files to Run</label></li>
							</ul>
						</div>
						
						<label>Email Recipient (whom to email when job is created):</label>
						<%= form.text_field :email_recipient, :class => "large", :placeholder=>"Email Recipient" %>
						<%= error_messages(@upload_type, "email_recipient") %>

						<label>Email ReplyTo (email address to include at bottom of all emails):</label>
						<%= form.text_field :email_replyto, :class => "large", :placeholder=>"ReplyTo" %>
						<%= error_messages(@upload_type, "email_replyto") %>
						
						<br/>
						<%= form.submit "Update", :class => 'btn btn-primary'%>
						<%= form.submit "Cancel", :name => 'cancel_button', :class => 'btn btn-primary'%>
					</fieldset>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/upload_types/index.html.erb
<div id="upload_types-page">
	<div id="page-content" class="clearfix">
		<h3>
			Upload Types
			<span class="pull-right">
				<%= link_to "New", new_upload_type_path, :class=>"btn btn-primary" %>
			</span>
		</h3>

		<div class="inner-box clearfix">
		  <div id="form-block" class="grid_15">
			  <% if @upload_types %>
			    <div id="table-block" class="grid_15">
			      <% unless @upload_types.nil? %>
		        <table class="table table-bordered table-hover table-condensed">
		          <tbody>
		            <thead>
									<td>Sort Order</td>
		              <td>Name</td>
		              <td>Tab Name</td>
		              <td class="text-center">Action</td>
		            </thead>
		            <%= render :partial => 'table_row', :collection => @upload_types %>
			          </tbody>
			        </table>
			      <% end %>
			    </div>
			  <% end %>
			</div>
		</div>
	</div>
</div>

app/views/upload_types/new.html.erb
<div id="upload_types-page">
	<div id="page-content" class="clearfix">
		<h1>New Upload Type</h1>

		<div class="inner-box clearfix">
		  <div id="form-block" class="grid_15">
				<%= form_for @upload_type, :url => upload_types_path do |form| %>
					<fieldset>
						<label>Name:</label>
						<%= form.text_field :name, :class => "large", :placeholder=>"Enter name of upload type" %>
						<%= error_messages(@upload_type, "name") %>

						<label>Tab Name:</label>
						<%= form.text_field :tab_name, :class => "large", :placeholder=>"Enter name for menu tab" %>
						<%= error_messages(@upload_type, "tab_name") %>

						<label>Description:</label>
						<%= form.text_area :description, :style=>"width:80%;height:100px", :placeholder=>"Enter description" %>
									
						<label>Upload Instructions:</label>
						<%= form.text_area :instructions, :style=>"width:80%;height:400px", :placeholder=>"Enter instructions for user" %>

						<label>Detailed Instructions about creating press-ready files:</label>
						<%= form.text_area :detailed_instructions, :style=>"width:80%;height:400px", :placeholder=>"Enter detailed instructions for user" %>

						<div class="well well-small">
							<ul class="unstyled">
							Upload Prompts to include:
								<li><label class="checkbox"><%= form.check_box :get_startdate %>StartDate</label></li>
								<li><label class="checkbox"><%= form.check_box :get_application_used %>Application Used (ie. InDesign, PhotoShop,...)</label></li>
								<li><label class="checkbox"><%= form.check_box :get_platform %>Platform (ie. Mac/Windows)</label></li>
								<li><label class="checkbox"><%= form.check_box :get_image_format %>Image Format (ie. TIFF, JPG,...)</label></li>
								<li><label class="checkbox"><%= form.check_box :get_vector_format %>Vector Format (ie. EPS, AI,...)</label></li>
								<li><label class="checkbox"><%= form.check_box :get_color_spec %>Color Spec (BW or Color)</label></li>
								<li><label class="checkbox"><%= form.check_box :get_job_type %>Job Types (ie. Coupon, Reverse,...)</label></li>
								<li><label class="checkbox"><%= form.check_box :get_trapping %>Trapping Applied?</label></li>
								<li><label class="checkbox"><%= form.check_box :get_files_to_run %>List of Files to Run</label></li>
							</ul>
						</div>

						<label>Email Recipient (whom to email when job is created):</label>
						<%= form.text_field :email_recipient, :class => "large", :placeholder=>"email" %>
						<%= error_messages(@upload_type, "email_recipient") %>

						<label>Email ReplyTo (email address to include at bottom of all emails):</label>
						<%= form.text_field :email_replyto, :class => "large", :placeholder=>"ReplyTo" %>
						<%= error_messages(@upload_type, "email_replyto") %>

						<br/>
						<%= form.submit "Create", :class => 'btn btn-primary'%>
						<%= form.submit "Cancel", :name => 'cancel_button', :class => 'btn btn-primary'%>
					</fieldset>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/upload_types/show.html.erb
<div id="upload_types-page">
	<div id="page-content" class="clearfix">
		<h3>
			Upload <%= @upload_type.name %>
			<span class="pull-right">
				<%= link_to "Upload New Job", new_job_path(:upload_job_id => @upload_type.id), :class=>"btn btn-primary" %>
			</span>
		</h3>

		<div class="inner-box clearfix">
		  <div id="form-block" class="grid_15">
				<p class="lead"><%= @upload_type.description %></p>
				<p><%= @upload_type.instructions.html_safe if @upload_type.instructions %></p>
			</div>
		</div>
	</div>
</div>