config/routes.rb
AdUpload::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
  
  resources :global_settings
  resources :email_texts
  
  resources :upload_types do
    get :detailed_instructions
  end
  
  resources :jobs
  get 'myjobs', :to => "jobs#myjobs"

  resources :job_files do
    post :approve
    post :reject
    get :download
  end
end

app/views/layouts/_footer.html.erb
<footer id="footer">
  <div class="row-fluid">
		<div class="span12">
		</div>
	</div>
  <div class="row-fluid">
		<div class="span12">
			<div id="copyright" class="text-center">
				<strong><a href="http://www.bendbulletin.com">EO Media Group LLC</a></strong> - &copy; Copyright 2013-<%= Date.today.year %>
			</div>
		</div>
	</div>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
	<nav class="navbar-inner">
		<div>
			<div class="span3 offset1">
				<h2>Ads.bendbulletin.com <small></small></h2>
			</div>
			<div class="pull-right">
				<ul class="nav">
				  <% if user_signed_in? %>
				    <li>
				    	<%= link_to current_user.email, edit_user_path(current_user) %>
				    </li>
				    <li>
				    	<%= link_to "Account", edit_user_path(current_user) %>
				    </li>
				    <li>
				    	<%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
				    </li>
				    <% if (current_user.has_role? :admin) or (current_user.has_role? :edit) %>
							<li class="dropdown">
							  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
							    Admin Tools
							    <b class="caret"></b>
							  </a>
							  <ul class="dropdown-menu">
									<% if (current_user.has_role? :admin) %>
										<li><%= link_to "Users", users_path %></li>
										<li><%= link_to "Global Setup", global_settings_path %></li>
										<li><%= link_to "Email Setup", email_texts_path %></li>
									<% else %>
										<li class="disabled"><%= link_to "Users", users_path %></li>
										<li class="disabled"><%= link_to "Setup", global_settings_path %></li>
									<% end %>
							  </ul>
				      </li>
					    <li></li>
				    <% end %>
				  <% end %>
				</ul>
		  </div>
		</div>
	</nav>
</div>

app/views/layouts/_header_no_links.html.erb
<div class="navbar navbar-fixed-top">
	<nav class="navbar-inner">
		<div>
			<div class="span3 offset1">
				<h2>Ads.bendbulletin.com <small></small></h2>
			</div>
			<div class="pull-right">
				<ul class="nav">
				</ul>
		  </div>
		</div>
	</nav>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<% if user_signed_in? %>
	<div class="navbar">
		<div class="navbar-inner">
		  <ul class="nav">
		    <li><%= link_to "Home", root_url %></li>
				<% if (current_user.has_role? :view) %>
	    		<li><%= link_to "My Jobs", myjobs_url %></li>
				<% else %>
	    		<li><%= link_to "All Jobs", jobs_url %></li>
				<% end %>
				<li><a> | </a></li>
				<% get_menu_tabs().each do |f| %>
			    <li><%= link_to f.tab_name, upload_type_path(f) %></li>
				<% end %>
		  </ul>
		</div>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Ads.bendbulletin.com" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Ads.bendbulletin.com" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>

  <body class="<%= controller_name %> <%= action_name %>">

		<%= render 'layouts/header' %>
		<%= render 'layouts/navigation' %>

    <div id="main" role="main">
      <div class="container-fluid">
        <div class="content">
           <div class="row-fluid">
            <div class="span12">
							<%= render :partial => 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
        </div>
      </div>
    </div>

		<%= render 'layouts/footer' %>

  </body>
</html>

app/views/layouts/detailed_instructions.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Detailed Upload Instructions" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Detailed Upload Instructions" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>

  <body class="<%= controller_name %> <%= action_name %>">
		<%= render 'layouts/header_no_links' %>
    <div id="main" role="main">
      <div class="container-fluid">
        <div class="content">
           <div class="row-fluid">
            <div class="span12">
              <%= yield %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>